# zmodload zsh/zprof

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source "$ZDOTDIR"/thirdparty/powerlevel10k/powerlevel10k.zsh-theme

for ZSH_FILE in "$ZDOTDIR"/*.zsh; do
    source "$ZSH_FILE"
done

#bindkey '^R' history-incremental-search-backward

eval "$(direnv hook zsh)"

# Refresh zcompdump only once every 24 hours
# zstyle :compinstall filename "$HOME"/.zshrc
# autoload -Uz compinit
# if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
# 	compinit;
# else
# 	compinit -C;
# fi;

# zprof
