[data]
sentry = false

# Not used by default, but kept here for posterity
[data.graphical]
enable = false
background = ""
outputs = ""
output_even = ""
output_odd = ""
flavours_i3status = ""
flavours_mako = ""
terminal_font = ""
